packages:
  - ./
  - ./playground

catalogs:
  deps:
    chokidar: ^4.0.3
    defu: ^6.1.4
    knitwork: ^1.2.0
    pathe: ^2.0.3
  dev:
    '@aa900031/eslint-config': ^3.2.0
    '@aa900031/release-it-config': ^0.1.0
    '@vitest/coverage-istanbul': ^3.2.4
    eslint: ^9.37.0
    release-it: ^19.0.5
    unbuild: ^3.6.1
    vitest: ^3.2.4
  peer:
    better-auth: ^1.3.27
    nitropack: ^2.12.7
  types:
    '@types/node': ^20.19.22
    typescript: ~5.9.3

onlyBuiltDependencies:
  - esbuild
